### ISSUE TITLE
Need Flutter App Migration from Previous Version (Android Embedding V2)

### ISSUE THREAD

**Issue by pspatel602** [moda20/flutter-tunein#1]

**Comment by moda20** [comment]
Hi,
What exactly do you mean by "Android Embedding V2" for this app. I know that it is a plugin feature, not an entire app.

**Comment by software-ace** [comment]
hey @moda20  check this https://stackoverflow.com/questions/59988211/what-is-the-difference-between-flutter-android-embedding-v1-and-v2 

and this https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

i forked this repo to create my first pull request ever but it seems like i have some errors after cloning it
Good Luck

**Comment by moda20** [comment]
@ahmadjehad 
@pspatel602 
The V2 update is up and tested, I have to actually update many plugins to make it work. 
Please don't forget to test the app.
i am closing this issue.
